version: '3'
services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    volumes:
      - ./:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
