# Generated by Django 3.1.2 on 2020-10-17 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sent_to',
        ),
        migrations.AddField(
            model_name='message',
            name='sent_to',
            field=models.ManyToManyField(related_name='messages_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
